name: Azure Deployment 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resources
        run: | 
          az deployment group create \
          --resource-group "${{ secrets.RESOURCE_GROUP_NAME }}" \
          --template-file ./bicep/main.bicep \
          # --verbose
          # --debug
